QT              += quick
HEADERS          = file_manager.hpp
SOURCES         += main.cpp file_manager.cpp
distribute.path  = /usr/share/quickfm
distribute.files = qml/*.qml icons/*.svgz
desktop.path     = /usr/share/applications
desktop.files    = quickfm.desktop
icon.path        = /usr/share/pixmaps
icon.files       = icons/folder.svgz
target.path      = /usr/bin
INSTALLS        += target distribute icon desktop
CONFIG          += c++11 debug qml_debug
