QT              += quick
HEADERS          = fm.hpp
SOURCES          = main.cpp fm.cpp
data.path        = /usr/share/quickfm
data.files       = qml/*.qml icons/*.svgz
desktop.path     = /usr/share/applications
desktop.files    = quickfm.desktop
icon.path        = /usr/share/pixmaps
icon.files       = icons/folder.svgz
target.path      = /usr/bin
INSTALLS         = target data icon desktop
CONFIG          += c++14 release #debug qml_debug
